config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    get "account/login", :to => "devise/sessions#new"
    delete "users/sign_out", :to => 'devise/sessions#destroy'
    post "users/sign_in", :to => 'session#create'
  end

  root 'site#show_page', :url => '/'

  namespace :admin do
    resources :content do
      collection do
        get :list
      end
    end
    resources :images, only: [:index]
    resources :menu, only: [:index]
    resources :site do
      collection do
        get :show_page
      end
    end
    resources :feedback do
      collection do
        get :show_form
      end
    end
  end

  resources :agencies do
    resources :locations do
      collection do
        get :get_cities_for_counties
        get :get_zips_for_counties
        get :get_counties_for_states
        post :get_cities_for_counties
        post :get_zips_for_counties
        post :get_counties_for_states
      end
    end
    resources :plans do
      collection do
        get :get_cities_for_counties
        get :get_zips_for_counties
        get :get_counties_for_states
      end
    end
    collection do
      get :go_to_agencies
      get :get_cities_for_counties
      get :get_zips_for_counties
      get :get_counties_for_states
      get :switch_counseling
      get :switch_active
      get :sort_plan
      post :ajax_search
      post :sort_plan
    end
  end

  resources :state do
    collection do
      get :catchall_employees
      post :sort_catchall_employee
    end
  end

  resources :publications

  resources :partners, only: [:index, :show, :edit, :destroy]

  resources :feedback do
    collection do
      post :save_feedback
    end
  end

  resources :feedbacks, only: [:index, :show, :update, :edit, :delete], :controller => :feedback do
    collection do
      get :show_form
    end
  end

  resources :help do
    collection do
      get :counseling
      get :resources
      get :step_2
      get :step_3
      get :step_5
      get :results
      get :last_step
      post :get_after_plan_selection_questions
      post :show_available_plans
      post :show_second_question
      post :show_third_question
      post :show_fourth_question
      post :show_fifth_question
      post :step_2
      post :email
      post :check_aoa_zip
      post :process_last_step
      post :process_step_3
      post :process_step_5
      post :get_counties
    end
  end

  resources :works, only: [:index, :create] do
    collection do
      get :pal
      get :npln
      get :questions
    end
  end

  match "/500", :to => "site#internal_error", via: [:get]

  get '*url', to: 'site#show_page'

end

app/models/publication.rb
# == Schema Information
#
# Table name: publications
#
#  id           :integer          not null, primary key
#  agency_id    :integer
#  tollfree     :string(20)
#  tollfree_ext :string(10)
#  phone        :string(20)
#  phone_ext    :string(10)
#  tty          :string(20)
#  tty_ext      :string(10)
#  fax          :string(20)
#  email        :string(255)
#  url          :string(255)
#  url_title    :string(255)
#  legacy_code  :string(10)
#  fmp2_code    :string(10)
#

class Publication < ActiveRecord::Base
  belongs_to :agency
  
  def empty?
    result = true
    attribute_names.each do |attr|
      unless attributes[attr].blank?
        result = false
      end
    end

    return result
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  # GET /publications
  # GET /publications.xml
  def index
    @publications = Publication.all

    respond_to do |format|
      format.html # index.rhtml
      format.xml  { render :xml => @publications.to_xml }
    end
  end

  # GET /publications/1
  # GET /publications/1.xml
  def show
    @publication = Publication.find(params[:id])

    respond_to do |format|
      format.html # show.rhtml
      format.xml  { render :xml => @publication.to_xml }
    end
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1;edit
  def edit
    @publication = Publication.find(params[:id])
  end

  # POST /publications
  # POST /publications.xml
  def create
    @publication = Publication.new(params[:publication])

    respond_to do |format|
      if @publication.save
        flash[:notice] = 'Publication was successfully created.'
        format.html { redirect_to publication_url(@publication) }
        format.xml  { head :created, :location => publication_url(@publication) }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @publication.errors.to_xml }
      end
    end
  end

  # PUT /publications/1
  # PUT /publications/1.xml
  def update
    @publication = Publication.find(params[:id])

    respond_to do |format|
      if @publication.update_attributes(params[:publication])
        flash[:notice] = 'Publication was successfully updated.'
        format.html { redirect_to publication_url(@publication) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @publication.errors.to_xml }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.xml
  def destroy
    @publication = Publication.find(params[:id])
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url }
      format.xml  { head :ok }
    end
  end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/edit.html.erb
<h1>Editing publication</h1>

<%= error_messages_for :publication %>

<% form_for(:publication, :url => publication_path(@publication), :html => { :method => :put }) do |f| %>
  <p>
    <b>Name</b><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <b>Phone</b><br />
    <%= f.text_field :phone %>
  </p>

  <p>
    <b>Phone ext</b><br />
    <%= f.text_field :phone_ext %>
  </p>

  <p>
    <b>Tollfree</b><br />
    <%= f.text_field :tollfree %>
  </p>

  <p>
    <b>Tollfree ext</b><br />
    <%= f.text_field :tollfree_ext %>
  </p>

  <p>
    <b>Fax</b><br />
    <%= f.text_field :fax %>
  </p>

  <p>
    <b>Tty</b><br />
    <%= f.text_field :tty %>
  </p>

  <p>
    <b>Tty ext</b><br />
    <%= f.text_field :tty_ext %>
  </p>

  <p>
    <b>Email</b><br />
    <%= f.text_field :email %>
  </p>

  <p>
    <b>Url</b><br />
    <%= f.text_field :url %>
  </p>

  <p>
    <b>Url title</b><br />
    <%= f.text_field :url_title %>
  </p>

  <p>
    <%= submit_tag "Update" %>
  </p>
<% end %>

<%= link_to 'Show', publication_path(@publication) %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<h1>Listing publications</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th>Phone ext</th>
    <th>Tollfree</th>
    <th>Tollfree ext</th>
    <th>Fax</th>
    <th>Tty</th>
    <th>Tty ext</th>
    <th>Email</th>
    <th>Url</th>
    <th>Url title</th>
  </tr>
  
<% @publications.each do |publication| %>
  <tr>
    <td><%=h publication.agency.name %></td>
    <td><%=h publication.phone %></td>
    <td><%=h publication.phone_ext %></td>
    <td><%=h publication.tollfree %></td>
    <td><%=h publication.tollfree_ext %></td>
    <td><%=h publication.fax %></td>
    <td><%=h publication.tty %></td>
    <td><%=h publication.tty_ext %></td>
    <td><%=h publication.email %></td>
    <td><%=h publication.url %></td>
    <td><%=h publication.url_title %></td>
    <td><%= link_to 'Show', publication_path(publication) %></td>
    <td><%= link_to 'Edit', edit_publication_path(publication) %></td>
    <td><%= link_to 'Destroy', publication_path(publication), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New publication', new_publication_path %>

app/views/publications/new.html.erb
<h1>New publication</h1>

<%= error_messages_for :publication %>

<% form_for(:publication, :url => publications_path) do |f| %>
  <p>
    <b>Name</b><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <b>Phone</b><br />
    <%= f.text_field :phone %>
  </p>

  <p>
    <b>Phone ext</b><br />
    <%= f.text_field :phone_ext %>
  </p>

  <p>
    <b>Tollfree</b><br />
    <%= f.text_field :tollfree %>
  </p>

  <p>
    <b>Tollfree ext</b><br />
    <%= f.text_field :tollfree_ext %>
  </p>

  <p>
    <b>Fax</b><br />
    <%= f.text_field :fax %>
  </p>

  <p>
    <b>Tty</b><br />
    <%= f.text_field :tty %>
  </p>

  <p>
    <b>Tty ext</b><br />
    <%= f.text_field :tty_ext %>
  </p>

  <p>
    <b>Email</b><br />
    <%= f.text_field :email %>
  </p>

  <p>
    <b>Url</b><br />
    <%= f.text_field :url %>
  </p>

  <p>
    <b>Url title</b><br />
    <%= f.text_field :url_title %>
  </p>

  <p>
    <%= submit_tag "Create" %>
  </p>
<% end %>

<%= link_to 'Back', publications_path %>

app/views/publications/show.html.erb
<p>
  <b>Name:</b>
  <%=h @publication.name %>
</p>

<p>
  <b>Phone:</b>
  <%=h @publication.phone %>
</p>

<p>
  <b>Phone ext:</b>
  <%=h @publication.phone_ext %>
</p>

<p>
  <b>Tollfree:</b>
  <%=h @publication.tollfree %>
</p>

<p>
  <b>Tollfree ext:</b>
  <%=h @publication.tollfree_ext %>
</p>

<p>
  <b>Fax:</b>
  <%=h @publication.fax %>
</p>

<p>
  <b>Tty:</b>
  <%=h @publication.tty %>
</p>

<p>
  <b>Tty ext:</b>
  <%=h @publication.tty_ext %>
</p>

<p>
  <b>Email:</b>
  <%=h @publication.email %>
</p>

<p>
  <b>Url:</b>
  <%=h @publication.url %>
</p>

<p>
  <b>Url title:</b>
  <%=h @publication.url_title %>
</p>


<%= link_to 'Edit', edit_publication_path(@publication) %> |
<%= link_to 'Back', publications_path %>