config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    get "account/login", :to => "devise/sessions#new"
    delete "users/sign_out", :to => 'devise/sessions#destroy'
    post "users/sign_in", :to => 'session#create'
  end

  root 'site#show_page', :url => '/'

  namespace :admin do
    resources :content do
      collection do
        get :list
      end
    end
    resources :images, only: [:index]
    resources :menu, only: [:index]
    resources :site do
      collection do
        get :show_page
      end
    end
    resources :feedback do
      collection do
        get :show_form
      end
    end
  end

  resources :agencies do
    resources :locations do
      collection do
        get :get_cities_for_counties
        get :get_zips_for_counties
        get :get_counties_for_states
        post :get_cities_for_counties
        post :get_zips_for_counties
        post :get_counties_for_states
      end
    end
    resources :plans do
      collection do
        get :get_cities_for_counties
        get :get_zips_for_counties
        get :get_counties_for_states
      end
    end
    collection do
      get :go_to_agencies
      get :get_cities_for_counties
      get :get_zips_for_counties
      get :get_counties_for_states
      get :switch_counseling
      get :switch_active
      get :sort_plan
      post :ajax_search
      post :sort_plan
    end
  end

  resources :state do
    collection do
      get :catchall_employees
      post :sort_catchall_employee
    end
  end

  resources :publications

  resources :partners, only: [:index, :show, :edit, :destroy]

  resources :feedback do
    collection do
      post :save_feedback
    end
  end

  resources :feedbacks, only: [:index, :show, :update, :edit, :delete], :controller => :feedback do
    collection do
      get :show_form
    end
  end

  resources :help do
    collection do
      get :counseling
      get :resources
      get :step_2
      get :step_3
      get :step_5
      get :results
      get :last_step
      post :get_after_plan_selection_questions
      post :show_available_plans
      post :show_second_question
      post :show_third_question
      post :show_fourth_question
      post :show_fifth_question
      post :step_2
      post :email
      post :check_aoa_zip
      post :process_last_step
      post :process_step_3
      post :process_step_5
      post :get_counties
    end
  end

  resources :works, only: [:index, :create] do
    collection do
      get :pal
      get :npln
      get :questions
    end
  end

  match "/500", :to => "site#internal_error", via: [:get]

  get '*url', to: 'site#show_page'

end

app/models/state.rb
# == Schema Information
#
# Table name: states
#
#  abbrev :string(2)        default(""), not null, primary key
#  name   :string(50)
#

class State < ActiveRecord::Base
  self.primary_key = 'abbrev'
  has_many :counties, :foreign_key => 'state_abbrev'
  
  def State.find_by_state_abbrevs(abbrevs)
    result = Array.new
    args = Array.new
    cond = ''
    unless abbrevs.nil?
      abbrevs.each_with_index do |abbrev,index|
        if index == 0
          cond += ' abbrev = ?'
        else
          cond += ' OR abbrev = ?'
        end
        args << abbrev
      end
      result = State.all.where([cond, args].flatten)
    end
    result
  end
  
  def State.agency_matches(state_abbrev)
    sql = <<-SQL
        select distinct a.*
        from agencies a
        join plans p on p.agency_id = a.id
        join restrictions r on r.plan_id = p.id
        join restrictions_states rs on rs.restriction_id = r.id
        left join restrictions_counties rc on rc.restriction_id = r.id
        left join restrictions_cities rci on rci.restriction_id = r.id
        where rc.county_id is null
        and rci.city_id is null
        and a.agency_category_id = 3
        and rs.state_abbrev = ?
        and a.use_for_counseling = 1 and a.is_active = 1 and p.is_active = 1
        SQL
    Agency.find_by_sql([sql, state_abbrev])
  end
  
  def plan_matches
    sql = <<-SQL
        select distinct p.*
        from plans p 
        join agencies a on p.agency_id = a.id
        join restrictions r on r.plan_id = p.id
        join restrictions_states rs on rs.restriction_id = r.id
        and a.agency_category_id = 3
        and rs.state_abbrev = ?
        and a.use_for_counseling = 1 and a.is_active = 1 and p.is_active = 1
        SQL
    Plan.find_by_sql([sql, abbrev])
  end
  
  def catchall_employees
    PlanCatchAllEmployee.all.where(['plan_id in (?)', State.agency_matches(self.abbrev).collect{|agency| agency.plans}.flatten]).order(:position)
    # State.agency_matches(self.abbrev).collect{|agency| agency.plans}.flatten.collect{|plan| plan.plan_catch_all_employees}.flatten
  end
  
end

app/controllers/state_controller.rb
class StateController < ApplicationController
  before_filter :authenticate_user!, :authorized?

  def authorized?
    current_user.is_admin?
  end

  def index
    @states=State.all
  end

  def catchall_employees
    @plan_employees=State.find(params[:id]).catchall_employees
  end

  def sort_catchall_employee
    params[:catchall_employee_list].each_with_index { |id,idx| PlanCatchAllEmployee.update(id, :position => idx) unless id.blank?}
    render :nothing => 'true'
  end
  
end

app/helpers/state_helper.rb
module StateHelper
end

app/views/state/catchall_employees.html.erb
<div id="content-no-sidebar" style="width: 760px">
<div class="admin_table">
<table id="catchall_employees" cellspacing="0">
	<tbody id="catchall_employee_list">
	<tr>
		<th colspan="4" id="table_title">CATCH-ALL EMPLOYEES</th>
	</tr>
	<tr>
		<th width="5%">drag to sort</th>
		<th>Employee Type</th>
      <th>Plan</th>
	</tr>
	<% @plan_employees.each_with_index do |plan_employee, i| %>
		<% plan = Plan.find(plan_employee.plan_id) %>
		<tr id="plan_<%=plan_employee.id.to_s%>" >
			<td class="center"><%= image_tag 'play.gif'%></td>
			<td><%= link_to h(EmployeeType.find(plan_employee.employee_type_id).name), edit_agency_plan_url(:agency_id => plan.agency_id, :id => plan) %></td>
			<td><%= link_to h(plan.name), edit_agency_plan_url(:agency_id => plan.agency_id, :id => plan) %></td>
		</tr>
	<% end %>
	</tbody>
</table>
</div><br/>
<div id="catchall_save">
<%= button_to 'Save and Return to List', state_index_path, :class => "center", method: :get %>
</div>

<%= sortable_element 'catchall_employee_list', 
			:tag => 'tr',
      :url => { :action => "sort_catchall_employee" } %>

</div>

app/views/state/index.html.erb
<div id="content-no-sidebar" style="width: 760px">
  <div id="return_button">
  <%= button_to 'Back to Management Menu', admin_menu_index_path, :method => :get %>
  </div>
  <div class="admin_table">
  <table id="plan_table" cellspacing="0">
          <tbody id="plan_list">          
                          <tr>
                                <th>State</th>
                                <th>Catchall Employees</th>
                          </tr>
                          <% @states.each do |state| %>
                          <tr  class="<%= cycle('odd','even') %>">
                                  <td><%= link_to h(state.name), :action => :catchall_employees, :id => state %></td>
                                  <td><%= state.catchall_employees.collect{|emp| EmployeeType.find(emp.employee_type_id).name}.join(', ') %></td>
                          </tr>
                          <% end %>
          </tbody>
  </table>
  </div>
</div>