config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    get "account/login", :to => "devise/sessions#new"
    delete "users/sign_out", :to => 'devise/sessions#destroy'
    post "users/sign_in", :to => 'session#create'
  end

  root 'site#show_page', :url => '/'

  namespace :admin do
    resources :content do
      collection do
        get :list
      end
    end
    resources :images, only: [:index]
    resources :menu, only: [:index]
    resources :site do
      collection do
        get :show_page
      end
    end
    resources :feedback do
      collection do
        get :show_form
      end
    end
  end

  resources :agencies do
    resources :locations do
      collection do
        get :get_cities_for_counties
        get :get_zips_for_counties
        get :get_counties_for_states
        post :get_cities_for_counties
        post :get_zips_for_counties
        post :get_counties_for_states
      end
    end
    resources :plans do
      collection do
        get :get_cities_for_counties
        get :get_zips_for_counties
        get :get_counties_for_states
      end
    end
    collection do
      get :go_to_agencies
      get :get_cities_for_counties
      get :get_zips_for_counties
      get :get_counties_for_states
      get :switch_counseling
      get :switch_active
      get :sort_plan
      post :ajax_search
      post :sort_plan
    end
  end

  resources :state do
    collection do
      get :catchall_employees
      post :sort_catchall_employee
    end
  end

  resources :publications

  resources :partners, only: [:index, :show, :edit, :destroy]

  resources :feedback do
    collection do
      post :save_feedback
    end
  end

  resources :feedbacks, only: [:index, :show, :update, :edit, :delete], :controller => :feedback do
    collection do
      get :show_form
    end
  end

  resources :help do
    collection do
      get :counseling
      get :resources
      get :step_2
      get :step_3
      get :step_5
      get :results
      get :last_step
      post :get_after_plan_selection_questions
      post :show_available_plans
      post :show_second_question
      post :show_third_question
      post :show_fourth_question
      post :show_fifth_question
      post :step_2
      post :email
      post :check_aoa_zip
      post :process_last_step
      post :process_step_3
      post :process_step_5
      post :get_counties
    end
  end

  resources :works, only: [:index, :create] do
    collection do
      get :pal
      get :npln
      get :questions
    end
  end

  match "/500", :to => "site#internal_error", via: [:get]

  get '*url', to: 'site#show_page'

end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  before_filter :authenticate_user!, :authorized?, :except => :show

  def authorized?
    current_user.is_admin?
  end

  def index
    @restriction = Restriction.new

    ajax_search
    render :action => :area_served_search
   end

  # GET /agencies/1
  # GET /agencies/1.xml
  def show
    @agency = Agency.find(params[:id])
    redirect_to edit_agency_url(@agency)
  end

  # GET /agencies/new
  def new
    @agency = Agency.new
    @agency.build_restriction
    @agency.publications.build
    #set default values
    @agency.is_active=true
    @agency.use_for_counseling=true
    render 'agencies/edit'
  end

  # GET /agencies/1;edit
  def edit
    order = SORT_ORDER_LOC[params[:order]] if params[:order]
    @agency = Agency.find(params[:id])
    @locations = Location.joins(:dropin_address).where(agency_id: params[:id]).order(order)
    @plans = Plan.where(agency_id: params[:id]).order('position')
    #@agency.build_restriction if !@agency.restriction
  end

  # POST /agencies
  # POST /agencies.xml
  def create
    if params['cancel']
      redirect_to agencies_url and return
    end
    @agency = Agency.new(agencies_params)
    @agency.updated_by = current_user.login

    publication = Publication.new(publication_params)
    @agency.publications << publication unless publication.empty?

    #@agency.build_restriction
    #@agency.restriction.update_attributes(params[:restriction])
    #@agency.restriction.states=params[:state_abbrevs].collect{|s| State.find(s)} unless params[:state_abbrevs].to_s.blank?
    #@agency.restriction.counties=params[:county_ids].collect{|c| County.find(c)} unless params[:county_ids].nil?
    #@agency.restriction.cities=params[:city_ids].collect{|c| City.find(c)} unless params[:city_ids].nil?
    #@agency.restriction.zips=params[:zip_ids].collect{|c| Zip.find(c)} unless params[:zip_ids].nil?

    #composed_of fields must be created manually
    update_pha_contact

    if @agency.save
      flash[:notice] = 'Agency was successfully created.'
      redirect_to agencies_url() and return if params['update_and_return']
      redirect_to edit_agency_url(@agency)
    else
      render :action => "new"
    end
  end

  # check if user clicked back button - if yes, set 'back' param to true
  # 'back' param is used for not to clear filter
  def go_to_agencies
    if params[:back]
      session[:back] = true
    else
      session[:back] = false
      redirect_to agencies_url(:clear=>true)
    end
  end


  # PUT /agencies/1
  # PUT /agencies/1.xml
  def update
    if params['cancel']
      redirect_to agencies_url and return
    end
    @agency = Agency.find(params[:id])
    @agency.updated_by = current_user.login
    if @agency.publication
      @agency.publications[0].update_attributes(publication_params)
    else
      publication = Publication.new(publication_params)
      unless publication.empty?
        @agency.publications << publication
        @agency.publications.last.save!
      end
    end
#    @agency.build_restriction if !@agency.restriction
#
#    @agency.restriction.update_attributes(params[:restriction])
#    @agency.restriction.states=params[:state_abbrevs].collect{|s| State.find(s)} unless params[:state_abbrevs].to_s.blank?
#    @agency.restriction.counties=params[:county_ids].collect{|c| County.find(c)} unless params[:county_ids].nil?
#    @agency.restriction.cities=params[:city_ids].collect{|c| City.find(c)} unless params[:city_ids].nil?
#    @agency.restriction.zips=params[:zip_ids].collect{|c| Zip.find(c)} unless params[:zip_ids].nil?

    #composed_of fields must be created manually
    update_pha_contact

    begin
      if @agency.update_attributes(agencies_params)
        flash[:notice] = 'Agency was successfully updated.'
        redirect_to agencies_url() and return if params['update_and_return']
        redirect_to edit_agency_url(@agency)
      else
        render :action => "edit"
      end
    end
  end

  # DELETE /agencies/1
  # DELETE /agencies/1.xml
  def destroy
    @agency = Agency.find(params[:id])
    @agency.destroy
    redirect_to agencies_url
  end

  def switch_counseling
    if (agency=Agency.find(params[:id]))
      agency.update_attribute(:use_for_counseling, !agency.use_for_counseling)
    end
    render :partial => 'agencies/counseling_check', :layout => false, :locals => {:agency => agency}
  end

  def switch_active
    if (agency=Agency.find(params[:id]))
      agency.update_attribute(:is_active, !agency.is_active)
    end
    render :partial => 'agencies/active_check', :layout => false, :locals => {:agency => agency}
  end

  def sort_location
    params[:location_list].each_with_index { |id,idx| Location.update(id, :position => idx) }
    render :nothing => 'true'
  end

  def sort_plan
    params[:plan_list].each_with_index { |id,idx| Plan.update(id, :position => idx) unless id.blank? }
    render :nothing => 'true'
  end

  def ajax_search

    session[:agency_order] = session[:agency_desc] = nil if (params[:clear] && session[:back]) # clear any params from session if this is our first time here
    params[:order] ||= session[:agency_order] # retrieve any existing params from the session
    params[:desc] ||= session[:agency_desc] unless params[:order] # don't override params[:desc] if we're passing in params[:order]
    session[:agency_order] = params[:order]   # save these params to session so they'll be 'remembered' on the next visit
    session[:agency_desc] = params[:desc]

    filter = find_search_filter
    filter.put_params(params, session[:back])

    params[:state_abbrevs] = filter.get_states
    params[:county_ids] = filter.get_counties
    params[:city_ids] = filter.get_cities
    params[:zip_ids] = filter.get_zips

    @selected_states = State.find_by_state_abbrevs(filter.get_states)
    @selected_counties = filter.get_counties.collect {|id| County.find(id)} if filter.get_counties
    filter.set_param('active', '1') unless filter.get_active
    filter.set_param('counseling', '1') unless filter.get_counseling
    params[:agency_category_id] = filter.get_category
    params[:counseling] = filter.get_counseling
    params[:active] = filter.get_active
    params[:provider] = filter.get_provider_type
    params[:agency_name] = filter.get_agency_name

    order = params[:order].nil? ? 'default' : params[:order]
    dir = params[:desc].nil? ? 1 : -1

    search_results = Agency.find_agencies filter
    @search_results = Agency.sort_agencies(search_results, order, dir)
  end

  private
  def update_pha_contact
    @agency.pha_contact = PhaContact.new(params[:pha_contact][:name], params[:pha_contact][:title],
      params[:pha_contact][:phone], params[:pha_contact][:email])
  end

  # peculiar category order due to TRAC #82 (https://prc.gradientblue.com/trac/pha/ticket/82)
#  CATEGORY_SORT = 'if(agencies.agency_category_id is null or agencies.agency_category_id="", "9999", agencies.agency_category_id)'
#  STATE_SORT = 'if(addresses.state_abbrev is null or addresses.state_abbrev="", "ZZZ", addresses.state_abbrev)'
#  RESULT_SORT = 'if(agencies.result_type_id is null or agencies.result_type_id="", "9999", agencies.result_type_id)'

#  SORT_ORDER = {
#    'default' => CATEGORY_SORT + ', ' + STATE_SORT + ', agencies.name asc',
#    'name' => 'agencies.name',
#    'state' => STATE_SORT + ', agencies.name',
#    'category' => CATEGORY_SORT + ', ' + STATE_SORT + ', agencies.name',
#    'result' => RESULT_SORT + ', agencies.name',
#    'counseling' => 'agencies.use_for_counseling desc, ' + CATEGORY_SORT + ', agencies.name',
#    'active' => 'agencies.is_active desc, ' + CATEGORY_SORT + ', agencies.name',
#    'name_desc' => 'agencies.name desc',
#    'state_desc' => STATE_SORT + ' desc , agencies.name',
#    'category_desc' => CATEGORY_SORT + ' desc , ' + STATE_SORT + ', agencies.name',
#    'result_desc' => RESULT_SORT + ' desc , agencies.name',
#    'counseling_desc' => 'agencies.use_for_counseling asc, ' + CATEGORY_SORT + ', agencies.name',
#    'active_desc' => 'agencies.is_active asc, ' + CATEGORY_SORT + ', agencies.name',
#    'provider' => CATEGORY_SORT + ', ' + STATE_SORT + ', agencies.name asc'
    #commenting out changes below pending ticket #211
    #client doesn't want to implement partial fixes for #211 until all the sorting is complete
    # 'default' => CATEGORY_SORT + ', ' + STATE_SORT + ', agencies.name asc',
    # 'name' => 'agencies.name',
    # 'state' => STATE_SORT + ', ' + CATEGORY_SORT + ', ' + RESULT_SORT + ', agencies.name',
    # 'category' => CATEGORY_SORT + ', ' + RESULT_SORT + ', agencies.name',
    # 'result' => RESULT_SORT + ', ' + CATEGORY_SORT  + ', agencies.name',
    # 'counseling' => 'agencies.use_for_counseling desc, ' + CATEGORY_SORT + ' desc , ' + RESULT_SORT + ', agencies.name',
    # 'active' => 'agencies.is_active desc, ' + 'agencies.use_for_counseling desc, ' + CATEGORY_SORT + ' desc , ' + RESULT_SORT + ', agencies.name',
    # 'name_desc' => 'agencies.name desc',
    # 'state_desc' => STATE_SORT + 'desc , ' + CATEGORY_SORT + ', ' + RESULT_SORT + ',  agencies.name',
    # 'category_desc' => CATEGORY_SORT + ' desc , ' + RESULT_SORT + ', agencies.name',
    # 'result_desc' => RESULT_SORT + 'desc , ' + CATEGORY_SORT  + ', agencies.name',
    # 'counseling_desc' => 'agencies.use_for_counseling asc, ' + CATEGORY_SORT + ' desc , ' + RESULT_SORT + ', agencies.name',
    # 'active_desc' => 'agencies.is_active asc, ' + 'agencies.use_for_counseling desc, ' + CATEGORY_SORT + ' desc , ' + RESULT_SORT + ', agencies.name',
    # 'provider' => 'agencies.use_for_counseling desc, ' + CATEGORY_SORT + ' desc , ' + RESULT_SORT + ', agencies.name',
#  }

  SORT_ORDER_LOC = {
    'name' => 'locations.name',
    'state' => 'COALESCE(NULLIF(addresses.state_abbrev, ""), "ZZZ"), locations.name'
  }
  def find_search_filter
    if (@SearchAreaFilter)
      @SearchAreaFilter = SearchAreaFilter.from_json(session[:search_filter])
    else

app/helpers/agencies_helper.rb
module AgenciesHelper

  #Prepares link_to_remote for Served Area page,
  #options contains new values for params, or markers for omitting those params
  def agencies_filter_link_to_remote(label ,params, options = {})
    link_to_remote label,
        :update => 'search_results',
        :url => render_url_from_params(params, options),
        :before => "Element.show('spinner')",
        :complete => "Element.hide('spinner')"
  end

  def agencies_filter_button_to_remote(label, params, options = {})

    function = remote_function(:update => 'search_results',
        :url => render_url_from_params(params, options),
        :before => "Element.show('spinner')",
        :complete => "Element.hide('spinner')")

    "<input type=\"button\" name=\"\" value=\"#{label}\" onclick=\"#{function}\" />"
  end

  def agencies_filter_button_to_clear()
    button =<<-END_BUTTON
    <form class="button-to" action="/agencies" method="get">
      <div>
      <input type="hidden" name="clear" value="true" />
      <input type="submit" name="submit" value="Show all agencies" />
      </div>
    </form>
    END_BUTTON
    return button
  end

  private

  def render_url_from_params(params, options)
    url = Hash.new
    #these params does not change
    url[:action] = :ajax_search
    url[:report] = 'search'
    SEARCH_PARAMS.each do |param|
      #this param's value should be replaced
      if options.has_key?(param)
        #replace default value of param or ommit param (eg if options[:active] = nil do not add this params to hash)
        url[param] = options[param] unless options[param].nil?
      else
        url[param] = params[param]
      end
    end
    url
  end

  SEARCH_PARAMS = [
      :state_abbrevs, :county_ids, :city_ids, :zip_ids, :order,
      :active, :desc, :counseling, :agency_category_id, :provider, :commit,
      :agency_name
  ]
end

app/views/agencies/_active_check.html.erb
<%= link_to_remote image_tag(agency.is_active ? 'check_blue.gif' : 'close.gif'),
		{:update => 'active_'+agency.id.to_s,
		:url => {:controller => 'agencies', :action => 'switch_active', :id => agency.id}, :remote => true}  %>

app/views/agencies/_counseling_check.html.erb
<%= link_to_remote image_tag(agency.use_for_counseling ? 'check_blue.gif' : 'close.gif'),
		{:update => 'use_for_counseling_'+agency.id.to_s,
		:url => {:controller => 'agencies', :action => 'switch_counseling', :id => agency.id}, :remote => true}  %>

app/views/agencies/edit.html.erb
<div id="content-no-sidebar">

<h2>Agency / Plan Administration</h2>

<%= error_messages_for :agency %>

  <%= form_for(:agency, :url => (@agency.id ? agency_path(@agency) : agencies_path), :html => { :method => (@agency.id ? :put : :post) , :class => 'admin_form' }) do |f| %>
    <div class="clear">
      <%= submit_tag " Update Agency ", :class => 'btn' %>
      <%= submit_tag " Update Agency and Return to List ", :name => 'update_and_return', :class => 'btn' %>
      <%= submit_tag ' Return to Agency List Without Saving ', :name=>'cancel', :class => 'btn' %>
    </div>
    <div id="agency_details" class="left agency_header fullwidth">
      <span><b>Category: </b><%= select :agency, :agency_category, AgencyCategory.order('position').all.collect{|c| [c.name, c.name]}, {:selected => (@agency.agency_category ? @agency.agency_category.name : "")}%>
      &nbsp;&nbsp;</span>
      <span><b>Result Type: </b><%= select :agency, :result_type, ResultType.order('position').all.collect{|c| [c.name, c.name]}, {:selected => (@agency.result_type ? @agency.result_type.name : "")}%>
      &nbsp;&nbsp;&nbsp;</span>
      <span class="regular-label">
        <b>
          <label for="agency_is_active">Active:</label>
        </b>
        <%= f.check_box :is_active %>&nbsp;&nbsp;&nbsp;
      </span>
      <span class="regular-label">
        <b>
          <label for="agency_use_for_counseling">Use for counseling:
        </b>
        <%= f.check_box :use_for_counseling %>&nbsp;&nbsp;&nbsp;
      </span>
      <span><b>Last updated: </b>
        <% if @agency.updated_at %><%= @agency.updated_at.strftime("%m/%d/%Y %I:%M %p")%><% end %>
        <% if @agency.updated_by %> by <%= @agency.updated_by %><% end -%></span>
    </div>
    <ul>
    <li class="clear left fullwidth">
        <div class=""><%= f.text_field :name, {:size => 130}  %>
        <label for="agency_name1">Agency Name 1</label></div>
        <div class=""><%= f.text_field :name2, {:size => 130}  %>
        <label for="agency_name2">Agency Name 2</label></div>
    </li>
    </ul>
    <ul class="clear left fullwidth">
    <li class="clear left ">
        <fieldset><div class="left"><%= f.text_field :url_title, {:size => 62} %>
        <label for="agency_url_title">URL Title (for display)</label></div>
        <div class="left"><%= f.text_field :url, {:size => 62}  %>
        <label for="agency_url">URL</label></div></fieldset>
        <fieldset><div class="left"><%= f.text_field :url2_title, {:size => 62} %>
        <label for="agency_url_title">URL2 Title (for display)</label></div>
        <div class="left"><%= f.text_field :url2, {:size => 62}  %>
        <label for="agency_url">URL2</label></div></fieldset>
    </li>
    <li class="left ">
      <span><%= f.text_area :description, :rows => 6, :cols => 60 %>
      <label>Description</label></span>
    </li>
    <li class="left ">
      <span><%= f.text_area :comments, :rows => 6, :cols => 60 %>
      <label>Comments</label></span>
    </li>
    <%# Agencies do not have any restrictions. See TRAC #63
     render :partial => '/shared/restrictions', :locals => {:restriction => @agency.restriction} %>
    <li class="left" id="phone_web">
      <%= fields_for :publication, @agency.publication do |pub| %>
        <fieldset><legend class="desc">Publication Contact Information</legend>
        <fieldset class="left">
        <span><%= pub.text_field :tollfree, :size => 15 %><label for="tollfree">Toll Free Phone</label></span>
        <span><%= pub.text_field :tollfree_ext, :size => 8 %><label for="tollfree">Ext</label></span>
        </fieldset>
        <fieldset class="left">
        <span><%= pub.text_field :phone, :size => 15 %><label for="local">Local Phone</label></span>
        <span><%= pub.text_field :phone_ext, :size => 8 %><label for="tollfree">Ext</label></span>
        </fieldset>
        <fieldset class="left">
        <span><%= pub.text_field :tty, :size => 15 %><label for="tty">TTY</label></span>
        <span><%= pub.text_field :tty_ext, :size => 8 %><label for="tollfree">Ext</label></span>
        </fieldset>
        <fieldset class="left">
        <span><%= pub.text_field :fax, :size => 15 %><label for="fax">Fax</label></span>
        </fieldset>
        <div class="clear left"><%= pub.text_field :url_title, {:size => 62} %>
        <label for="agency_url_title">Publication URL Title (for display)</label></div>
        <div class="left"><%= pub.text_field :url, {:size => 62}  %>
        <label for="agency_url">Publication URL</label></div>
        <div class="clear left"><%= pub.text_field :email, :size => 30 %><label for="email">Email</label></div>
        </fieldset>
      <% end %>
    </li>
                <li class="left" id="pha_contact">
                  <%= render :partial => 'shared/pha_contact', :object => @agency.pha_contact %>
                </li>
    </ul>
    <div class="left fullwidth">
    <div class="admin_table">
      <table id="loc_table" cellspacing="0">
        <tbody id="location_list">
        <tr><th colspan="8" id="table_title"><h3>AGENCY LOCATIONS</h3></th></tr>
        <% if @locations %>
          <tr>
            <th class="hq">HQ</th>
            <th class="hq">Provider</th>
            <th class="loc"><%= link_to 'Location', edit_agency_path(:order=>'name') %></th>
            <th class="city">City, <%= link_to 'State', edit_agency_path(:order=>'state') %></th>
            <th class="">Age</th>
            <th class="">FPG</th>
            <th class="">AND</th>
            <th class="">Active</th>
          </tr>
          <% @locations.each_with_index do |location, i| %>
          <tr id="location_<%=location.id.to_s%>" class="<%= 'disabledLocation' unless location.is_active %>">
            <td class="hq"><%= location.is_hq? ? image_tag('check.gif') : '&nbsp;'.html_safe  %></td>
            <td class="hq"><%= location.is_provider? ? image_tag('check_blue.gif')  : '&nbsp;'.html_safe %></td>
            <td class="loc "><%= link_to h(location.name), edit_agency_location_url(:agency_id => @agency, :id => location) %></td>
            <td class="city "><%  if location.dropin_address -%>
              <%= location.dropin_address.city %><% if !location.dropin_address.city.blank? %>, <% end %><%= location.dropin_address.state_abbrev %>
            <%end %></td>
            <td><%= location.age_restrictions? ? image_tag('check.gif') : '&nbsp;'.html_safe %></td>
            <td><%= location.income_restrictions? ? image_tag('check.gif') : '&nbsp;'.html_safe %></td>
            <td><%= location.and_restrictions? ? image_tag('check.gif') : '&nbsp;'.html_safe %></td>
            <td><%= image_tag(location.is_active ? 'check_blue.gif' : 'close.gif')%></td>
          </tr>
          <% end %>
        <% end %>
        </tbody>
      </table>
      <% if @locations and @locations.empty? %><div class="none-found">No locations found</div><% end %>
      <% if @agency.new_record? %>
        Please save changes to this agency before adding locations
      <% else %>
        <%= link_to 'Add a new location ...',
            new_agency_location_path(@agency),
            :class => 'plain btn' %>
        <%= link_to_function 'Show/Hide inactive locations',
            "toggleRows('disabledLocation')",
            :id => 'showHideLocations',
            :class => 'btn' %>
      <% end -%>
    </div>
    <div class="admin_table">
      <table id="plan_table" cellspacing="0">
        <tbody id="plan_list">
        <tr>
          <th colspan="4" id="table_title"><h3>PLANS</h3></th></tr>
          <% if !@agency.new_record? %>
            <tr>
              <th width="5%">drag to sort</th>
              <th>Plan Name</th>
              <th>Active</th>
              <th>Catch-all Employees</th>
            </tr>
            <% @plans.each_with_index do |plan, i| %>
            <tr id="plan_<%=plan.id.to_s%>" class="<%= 'disabledPlan' unless plan.is_active %>">
              <td class="center"><%= image_tag 'play.gif'%></td>
              <td><%= link_to h(plan.name), edit_agency_plan_url(:agency_id => @agency, :id => plan)%></td>
              <td><%= image_tag(plan.is_active ? 'check_blue.gif' : 'close.gif') %></td>
              <td><%= plan.catchall_employees %></td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <% if @plans and @plans.empty? %><div class="none-found">No plans found</div><% end %>
      <% if @agency.new_record? %>
        Please save changes to this agency before adding plans
      <% else %>
        <%= link_to 'Add a new plan ...',
          new_agency_plan_path(@agency),
          :class => 'plain btn' %>
        <%= link_to_function 'Show/Hide inactive plans',
          "toggleRows('disabledPlan')",
          :id => 'showHidePlans',
          :class => 'btn' %>
      <% end -%>
      </div>
    </div>
    <div class="clear left fullwidth">
      <%= submit_tag " Update Agency ", :class => 'btn' %>
      <%= submit_tag " Update Agency and Return to List ", :name => 'update_and_return', :class => 'btn' %>
      <%= submit_tag ' Return to Agency List Without Saving ', :name=>'cancel', :class => 'btn' %>
    </div>
<% end %>

<%# re-ordering locations removed per #102.
sortable_element 'location_list',
      :tag => 'tr',
      :url => { :action => "sort_location" } %>

<%= sortable_element 'plan_list',
      :tag => 'tr',
      :url => { :action => "sort_plan" } %>

<script type="text/javascript">

    window.onbeforeunload = function() {
        new Ajax.Request('/agencies/go_to_agencies', {
            method:       'post',
            asynchronous: false,
            parameters: 'back=true'
        });
    };

  /* toggles all element with given class*/
  function toggleRows(elemClass) {
    $$("." + elemClass).each( function(e) {
      e.toggle()}
    );
    return false;
  }

  /* Hide inactive locations and plans. */
  Event.observe( window, 'load', function() {
    ['.disabledLocation', '.disabledPlan'].each(function(item) {
      $$(item).each(function(e_class) {
        e_class.hide();
      });
    });

    /*Add 'save reminder' to links and buttons */
    var asr = new AdminSaveReminder();
    asr.addObserverToLinkButtons(['showHideLocations','showHidePlans'], ['commit', 'update_and_return']);
  });
</script>


<script type="text/javascript">
  jQuery(document).ready(function(){
    jQuery("#publication_tollfree").mask("(999) 999-9999");
    jQuery("#publication_phone").mask("(999) 999-9999");
    jQuery("#publication_tty").mask("(999) 999-9999");
    jQuery("#publication_fax").mask("(999) 999-9999");
    jQuery("#pha_contact_phone").mask("(999) 999-9999");
   });
</script>

</div>

app/views/agencies/go_to_agencies.html.erb
<h1>go to agency</h1>

app/views/agencies/new.html.erb
<div id="content-no-sidebar">
<h1>New agency</h1>

<%= error_messages_for :agency %>

<% form_for(:agency, :url => agencies_path) do |f| %>
  <p>
    <b>Name</b><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <b>Name2</b><br />
    <%= f.text_field :name2 %>
  </p>

  <p>
    <b>Data source</b><br />
    <%= f.text_field :data_source %>
  </p>

  <p>
    <b><label for="agency_is_active">Active</label></b><br />
    <%= f.check_box :is_active %>
  </p>

  <p>
    <b>Url</b><br />
    <%= f.text_field :url %>
  </p>

  <p>
    <b>Url title</b><br />
    <%= f.text_field :url_title %>
  </p>

  <p>
    <%= submit_tag "Create" %>
  </p>
<% end %>


<%= link_to 'Back', agencies_path %>

  </div>

app/views/agencies/show.html.erb
<p>
  <b>Name:</b>
  <%=h @agency.name %>
</p>

<p>
  <b>Name2:</b>
  <%=h @agency.name2 %>
</p>

<p>
  <b>Data source:</b>
  <%=h @agency.data_source %>
</p>

<p>
  <b>Is active:</b>
  <%=h @agency.is_active %>
</p>

<p>
  <b>Url:</b>
  <%=h @agency.url %>
</p>

<p>
  <b>Url title:</b>
  <%=h @agency.url_title %>
</p>

<%= link_to 'Add location', new_location_path(@agency) %> |
<%= link_to 'Add plan', new_plan_path(@agency) %> |
<%= link_to 'Edit', edit_agency_path(@agency) %> |
<%= link_to 'Back', agencies_path %>