config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    get "account/login", :to => "devise/sessions#new"
    delete "users/sign_out", :to => 'devise/sessions#destroy'
    post "users/sign_in", :to => 'session#create'
  end

  root 'site#show_page', :url => '/'

  namespace :admin do
    resources :content do
      collection do
        get :list
      end
    end
    resources :images, only: [:index]
    resources :menu, only: [:index]
    resources :site do
      collection do
        get :show_page
      end
    end
    resources :feedback do
      collection do
        get :show_form
      end
    end
  end

  resources :agencies do
    resources :locations do
      collection do
        get :get_cities_for_counties
        get :get_zips_for_counties
        get :get_counties_for_states
        post :get_cities_for_counties
        post :get_zips_for_counties
        post :get_counties_for_states
      end
    end
    resources :plans do
      collection do
        get :get_cities_for_counties
        get :get_zips_for_counties
        get :get_counties_for_states
      end
    end
    collection do
      get :go_to_agencies
      get :get_cities_for_counties
      get :get_zips_for_counties
      get :get_counties_for_states
      get :switch_counseling
      get :switch_active
      get :sort_plan
      post :ajax_search
      post :sort_plan
    end
  end

  resources :state do
    collection do
      get :catchall_employees
      post :sort_catchall_employee
    end
  end

  resources :publications

  resources :partners, only: [:index, :show, :edit, :destroy]

  resources :feedback do
    collection do
      post :save_feedback
    end
  end

  resources :feedbacks, only: [:index, :show, :update, :edit, :delete], :controller => :feedback do
    collection do
      get :show_form
    end
  end

  resources :help do
    collection do
      get :counseling
      get :resources
      get :step_2
      get :step_3
      get :step_5
      get :results
      get :last_step
      post :get_after_plan_selection_questions
      post :show_available_plans
      post :show_second_question
      post :show_third_question
      post :show_fourth_question
      post :show_fifth_question
      post :step_2
      post :email
      post :check_aoa_zip
      post :process_last_step
      post :process_step_3
      post :process_step_5
      post :get_counties
    end
  end

  resources :works, only: [:index, :create] do
    collection do
      get :pal
      get :npln
      get :questions
    end
  end

  match "/500", :to => "site#internal_error", via: [:get]

  get '*url', to: 'site#show_page'

end

app/models/plan.rb
# == Schema Information
#
# Table name: plans
#
#  id                    :integer          not null, primary key
#  agency_id             :integer
#  name                  :string(255)
#  name2                 :string(255)
#  description           :text
#  comments              :text
#  start_date            :date
#  end_date              :date
#  covered_employees     :text
#  plan_type1            :string(255)
#  plan_type2            :string(255)
#  plan_type3            :string(255)
#  url                   :string(255)
#  url_title             :string(255)
#  admin_url             :string(255)
#  admin_url_title       :string(255)
#  tpa_url               :string(255)
#  tpa_url_title         :string(255)
#  spd_url               :string(255)
#  spd_url_title         :string(255)
#  govt_employee_type    :string(255)
#  fmp2_code             :string(255)
#  legacy_category       :string(255)
#  legacy_status         :string(255)
#  updated_at            :datetime
#  updated_by            :string(255)
#  email                 :string(255)
#  position              :integer
#  pha_contact_name      :string(255)
#  pha_contact_title     :string(255)
#  pha_contact_phone     :string(20)
#  pha_contact_email     :string(255)
#  is_active             :boolean          default(TRUE)
#  previous_gov_employee :string(255)
#  plan_category_id      :integer
#

require 'restrictions_updater'

class Plan < ActiveRecord::Base
  include RestrictionsUpdater
  belongs_to :agency
  belongs_to :plan_category
  has_one :publication
  has_many :restrictions, :dependent => :destroy
  has_many :plan_catch_all_employees, ->{order('position asc')}, :dependent => :destroy
  has_many :employee_types, :through => :plan_catch_all_employees
  has_many :location_plan_relationships, :dependent => :destroy
  has_many :serving_locations, :through => :location_plan_relationships, :source => :location
  before_save :update_employee_types, :update_serving_locations

  validates_presence_of     :name

  composed_of :pha_contact, :class_name => 'PhaContact',
    :mapping => [
      [:pha_contact_name, :name],
      [:pha_contact_title, :title],
      [:pha_contact_phone, :phone],
      [:pha_contact_email, :email],
    ]

  attr_accessor :new_locations, :location_hq

  def catchall_employees
    self.employee_types.collect{|et| et.name}.join(', ')
  end

  def catchall_employees=(value)
    @catchall_employees=value
  end

  def employee_list
    return nil if catchall_employees.blank?
    catchall_employees.split(', ').collect{|e| [e, id]}
  end

  def start_date_formatted
     start_date.strftime '%m/%d/%Y' if start_date
  end

  def start_date_formatted=(value)
     self.start_date = Date.parse(value) if !value.blank?
  end

  def end_date_formatted
     end_date.strftime '%m/%d/%Y' if end_date
  end

  def end_date_formatted=(value)
     self.end_date = Date.parse(value) if !value.blank?
  end

  def update_employee_types
    return if @catchall_employees.nil?
    @catchall_employees.split(', ').each do |e|
      # MySQL is case insensitive, so we grab all matching employees and do the comparisons on our own
      unless et=EmployeeType.all.where(['name = ?', e]).select{|emp| emp.name==e}.first
        et=EmployeeType.new
        et.name = e
        et.save!
      end
      pcae=PlanCatchAllEmployee.new(:employee_type_id => et.id, :plan_id => self.id)
      self.plan_catch_all_employees << pcae unless self.employee_types.include?(et)
    end
    plan_catch_all_employees.select{|item| !@catchall_employees.split(', ').include?( item.employee_type.name )}.each{|pcae| pcae.destroy}
  end

  # update list of locations that serve this plan
  def update_serving_locations
    unless new_locations.nil?
      self.location_plan_relationships.each do |relationship|
        relationship.update_attribute(:is_hq, relationship.location_id == location_hq)
        relationship.destroy unless new_locations.include?(relationship.location_id)
        new_locations.delete(relationship.location_id)
      end
      new_locations.each do |loc_id|
        self.location_plan_relationships.create(:location_id => loc_id, :is_hq=> loc_id == location_hq) unless loc_id.blank?
      end
      self.new_locations = nil
    end
  end

  def best_location(counseling)
    # out of state should find hq
    if (counseling.home_state_abbrev == serving_locations.first.dropin_address.state_abbrev rescue nil) # in home state
      closest_serving_location(counseling.home_zip)
    else  #out of state
      hq_serving_location
    end
  end

  def hq_serving_location
    potential_matches = self.location_plan_relationships
    return nil if potential_matches.empty?
    #use hq if available otherwise just return first match (admin probably forgot to assign a HQ for this plan)
    potential_matches.select{|rel| rel.is_hq}.first.location rescue potential_matches.first.location
  end

  def closest_serving_location(zip)
    serving_locations.map{|loc| loc.dropin_address}.sort_by{|a| a.distance_from(zip)}.first.location
  end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_filter :authenticate_user!, :authorized?
  before_filter :find_agency, 
                :except => [:get_counties_for_states, 
                            :get_cities_for_counties, 
                            :get_zips_for_counties,
                            :auto_complete_for_plan_catchall_employees]
  
  #auto_complete_for :plans, :catchall_employees
  
  def authorized?
    current_user.is_admin?
  end

  # GET /plans
  # GET /plans.xml
  def index
    redirect_to agencies_url
  end

  # GET /plans/1
  # GET /plans/1.xml
  def show
    redirect_to edit_agency_url(@agency) 
  end

  # GET /plans/new
  def new
    @plan = Plan.new
    @plan.agency = @agency
    @new_restrictions = @plan.get_empty_restrictions
    #@plan.build_restriction
    @plan.is_active = true
    render :template => 'plans/edit'
  end

  # GET /plans/1;edit
  def edit
    @plan = @agency.plans.find(params[:id])
    @new_restrictions = @plan.get_empty_restrictions
    #@plan.build_restriction if !@plan.restriction
  end

  # POST /plans
  # POST /plans.xml
  def create
    if params['cancel']
      redirect_to edit_agency_url(@agency) and return
    end
    @plan = @agency.plans.build(plans_parameters)
    @plan.updated_by = current_user.login
    params[:plan][:new_locations] ||= []  # in case no checkboxes are checked
    #@plan.build_restriction if !@plan.restriction
    #update_restriction

    update_pha_contact

    is_ok = true
    @plan.transaction do
      begin
        @plan.update_restrictions(params)
        @plan.save!
      rescue
        logger.error($!)
        is_ok = false
      end
    end

    if is_ok
      flash[:notice] = 'Plan was successfully created.'
      redirect_to edit_agency_url(@agency) and return if params['update_and_return']
      redirect_to agencies_path() and return if params['update_and_list']
      redirect_to edit_agency_plan_url(:agency_id => @agency, :id => @plan)
    else
      # setting object @new_restrictions in order to correct displaying partial _new_restriction_form.rhtml
      @new_restrictions = @plan.get_empty_restrictions
      render :template => 'plans/edit' 
    end
  end

  # PUT /plans/1
  # PUT /plans/1.xml
  def update
    if params['cancel']
      redirect_to edit_agency_url(@agency) and return
    end
    @plan = @agency.plans.find(params[:id])
    @plan.updated_by = current_user.login
    params[:plan][:new_locations] ||= []  # in case no checkboxes are checked
    #@plan.build_restriction if !@plan.restriction
    #update_restriction

    update_pha_contact
    
    is_ok = true
    @plan.transaction do
      begin
        @plan.update_attributes!(plans_parameters)
        @plan.update_restrictions(params)
      rescue
        logger.error($!)
        is_ok = false
      end
    end

    if is_ok
      flash[:notice] = 'Plan was successfully updated.'
      redirect_to edit_agency_url(@agency) and return if params['update_and_return']
      redirect_to agencies_path() and return if params['update_and_list']
      redirect_to edit_agency_plan_url(:agency_id => @agency, :id => @plan)
    else
      # setting object @new_restrictions in order to correct displaying partial _new_restriction_form.rhtml
      @new_restrictions = @plan.get_empty_restrictions
      render :edit
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.xml
  def destroy
    @plan = @agency.plans.find(params[:id])
    @plan.destroy
    redirect_to edit_agency_url(@agency)
  end

  def auto_complete_for_plan_catchall_employees
    render :inline => Plan.find(params[:id]).catchall_employees.split(', ').to_s, :layout => false
  end
  
  protected
  
  def find_agency
    @agency = Agency.find(params[:agency_id])
  end
  
  def update_pha_contact
    @plan.pha_contact = PhaContact.new(params[:pha_contact][:name], params[:pha_contact][:title],
      params[:pha_contact][:phone], params[:pha_contact][:email])
  end

  private

  def plans_parameters
    params.require(:plan).permit(:is_active, :name, :name2, :plan_type1, :plan_type2, :start_date_formatted, :end_date_formatted,
                                 :govt_employee_type,:description, :comments, :covered_employees, :catchall_employees, :url_title, :url,
                                 :email, :admin_url_title, :admin_url, :spd_url_title, :spd_url, :tpa_url_title, :tpa_url,:location_hq, new_locations: [],
    restriction_attr: [:id, :minimum_age, :age_restricted_phone, :max_poverty, :age_and_income, :special_district, :other_restrictions, :delete_marker, :plan_id, :create_new])
  end

end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_serving_locations_panel.html.erb
<div class="admin_table">
	<table id="location_table" cellspacing="0">
		<tbody id="location_list">
		<tr>
			<th colspan="4" id="table_title"><h2>Locations for <%= @plan.name %></h2></th></tr>
				<tr>
          <th class="center">Served by this Location</th>
					<th class="center">HQ for this Plan</th>
					<th>Location Name</th>
				</tr>
				<% @plan.agency.locations.sort_by{|l| l.name}.each_with_index do |location, i| %>
				<tr id="location_<%=location.id.to_s%>">
					<td class="center"><%= check_box_tag 'plan[new_locations][]', location.id, @plan.serving_locations.include?(location) %></td>
					<td class="center"><%= radio_button_tag "plan[location_hq]", location.id, (!@plan.location_plan_relationships.select{|rel| rel.location_id == location.id and rel.is_hq?}.empty? unless @plan.location_plan_relationships.empty?) %>
          <td><%= link_to location.name, edit_agency_location_url(@plan.agency, location) %></td>
				</tr>
				<% end %>
		</tbody>
	</table>
</div>

app/views/plans/edit.html.erb
<div id="content-no-sidebar">
<h2>Agency / Plan Administration</h2>

<h3 id="agency_heading"><label>Agency: </label><%= @agency.name %>:<%= @agency.name2 %></h3>
<%= error_messages_for :plan %>

  <%= form_for(:plan,
    :url => (@plan.id ? agency_plan_path(@agency, @plan) : agency_plans_path(@agency, @plan)),
    :html => { :method => (@plan.id ? :put : :post) , :class => 'admin_form', :id => 'plan_form' }) do |f| %>
    <br/>
    <div class="clear fullwidth buttons">
      <%= submit_tag " Update Plan ", :class => 'btn'  %>
      <%= submit_tag " Update Plan and Return to Agency ", :name => 'update_and_return', :class => 'btn' %>
      <%= submit_tag ' Return to Agency Without Saving ', :name=>'cancel', :class => 'btn' %>
      <%= submit_tag ' Update Plan and Return to List ', :name => 'update_and_list', :class => 'btn' %>
    </div>
    <div id="agency_details" class="left agency_header fullwidth">
      <span class="regular-label"><b><label for="plan_is_active">Active:</label> </b><%= f.check_box :is_active %>&nbsp;&nbsp;&nbsp;</span>
      <%if @plan.updated_at %>
        <span><b>Last updated: </b><%= @plan.updated_at.strftime("%m/%d/%Y %I:%M %p") if @plan.updated_at %>
        <%if @plan.updated_by %>by <%= @plan.updated_by %><% end %></span>
      <% end %>
    </div>


  <ul>
  <li class="clear left fullwidth">
    <div><%= f.text_field :name, :size => 142 %><label>Plan Name: </label></div>
    <div><%= f.text_field :name2, :size => 142 %><label>Plan Name 2: </label></div>
    <span><%= f.text_field :plan_type1, :size => 65 %><label>Plan Type 1</label></span>
    <span><%= f.text_field :plan_type2, :size => 65 %><label>Plan Type 2</label></span></li>
  <li class="clear left fullwidth">
    <span><%= f.text_field :start_date_formatted, :size => 15 %><label>Start Date</label></span>
    <span><%= f.text_field :end_date_formatted, :size => 15 %><label>End Date</label></span>
    <span><%= f.text_field :govt_employee_type, :size => 35 %><label>Government Employee Type</label></span>
  </li>
  <li class="clear left fullwidth">
    <fieldset><legend class="desc">Details</legend>
    <span><%= f.text_area :description, :rows => 6, :cols => 60 %>
    <label>Description</label></span>
    <span><%= f.text_area :comments, :rows => 6, :cols => 60 %>
    <label>Comments</label></span>
    <span><%= f.text_area :covered_employees, :rows => 6, :cols => 60 %>
    <label>Covered Employees</label></span>
    <span><%= f.text_area :catchall_employees, :rows => 6, :cols => 60 %>
    <label>Catch-all Employees</label></span>
    </fieldset>
  </li>
  <li class="clear left fullwidth">
    <span>
      <%#= f.text_field :catchall_employees %>
      <%#= text_field_with_auto_complete :plan, :catchall_employees, {}, :url =>{ :controller => 'plans', :action => 'auto_complete_for_plan_catchall_employees', :id => @plan.id }%>
    </span>
  </li>
  <%#= render :partial => '/shared/restrictions', :locals => {:restriction => @plan.restriction} %>
  <%= render :partial => '/shared/restrictions_panel',
    :locals => {:restrictions => @plan.restrictions, :new_restrictions => @new_restrictions, :is_location => false} %>


  <% unless @plan.agency.locations.empty? %>
  <li class="clear left">
    <%= render :partial => 'plans/serving_locations_panel' %>
  </li>
  <% end %>

  <li class="clear left fullwidth" id="phone_web">
        <fieldset class="clear left fullwidth"><legend class="desc">Plan Contact Information</legend>
        <fieldset class="clear left">
        <span><%= f.text_field :url_title, :size => 62 %><label for="tollfree">Plan URL Title</label></span>
        <span><%= f.text_field :url, :size => 62 %><label for="tollfree">Plan URL</label></span>
        <div class="clear left"><%= f.text_field :email, :size => 30 %><label for="email">Plan Email</label></div>
        </fieldset>
        <fieldset class="clear left">
        <span><%= f.text_field :admin_url_title, :size => 62 %><label for="local">Admin URL Title</label></span>
        <span><%= f.text_field :admin_url, :size => 62 %><label for="tollfree">Admin URL</label></span>
        </fieldset>
        <fieldset class="clear left">
        <span><%= f.text_field :spd_url_title, :size => 62 %><label for="tty">SPD URL Title</label></span>
        <span><%= f.text_field :spd_url, :size => 62 %><label for="tollfree">SPD URL</label></span>
        </fieldset>
        <fieldset class="clear left">
        <span><%= f.text_field :tpa_url_title, :size => 62 %><label for="tty">Third Party Administrator URL Title</label></span>
        <span><%= f.text_field :tpa_url, :size => 62 %><label for="tollfree">Third Party Administrator URL</label></span>
        </fieldset>
        </fieldset>
    </li>
    <li class="clear left fullwidth" id="pha_contact">
      <%= render :partial => 'shared/pha_contact', :object => @plan.pha_contact %>
    </li>
</ul>


  <div class="clear left fullwidth buttons">
    <%= submit_tag " Update Plan ", :class => 'btn'  %>
    <%= submit_tag " Update Plan and Return to Agency ", :name => 'update_and_return', :class => 'btn' %>
    <%= submit_tag ' Return to Agency Without Saving ', :name=>'cancel', :class => 'btn' %>
    <%= submit_tag ' Update Plan and Return to List ', :name => 'update_and_list', :class => 'btn' %>
  </div>

<% end %>
<script type="text/javascript">
  /* Hide inactive locations and plans. */
  Event.observe( window, 'load', function() {
    /*Add 'save reminder' to links and buttons */
    var asr = new AdminSaveReminder();
    asr.addObserverToLinkButtons(['geo_edit_link','addNewRestrictionLink'],
      ['commit', 'update_and_return', 'update_and_list'],
      ['plan[restriction_attr][-4][create_new]','plan[restriction_attr][-3][create_new]','plan[restriction_attr][-2][create_new]','plan[restriction_attr][-1][create_new]']);
  });
</script>

<script type="text/javascript">
  jQuery(document).ready(function(){
    jQuery("#pha_contact_phone").mask("(999) 999-9999");
   });
</script>

</div>

app/views/plans/index.html.erb
<h1>Listing plans</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Name2</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Covered employees</th>
    <th>Catchall employees</th>
    <th>Description</th>
    <th>Service description</th>
    <th>Comments</th>
    <th>Status</th>
    <th>Govt employee type</th>
    <th>Special district</th>
    <th>Plan type1</th>
    <th>Plan type2</th>
    <th>Plan type3</th>
    <th>Url</th>
    <th>Url title</th>
    <th>Admin url</th>
    <th>Admin url title</th>
    <th>Tpa url</th>
    <th>Tpa url title</th>
    <th>Spd url</th>
    <th>Spd url title</th>
  </tr>
  
<% for plan in @plans %>
  <tr>
    <td><%=h plan.name %></td>
    <td><%=h plan.name2 %></td>
    <td><%=h plan.start_date %></td>
    <td><%=h plan.end_date %></td>
    <td><%=h plan.covered_employees %></td>
    <td><%=h plan.catchall_employees %></td>
    <td><%=h plan.description %></td>
    <td><%=h plan.service_description %></td>
    <td><%=h plan.comments %></td>
    <td><%=h plan.status %></td>
    <td><%=h plan.govt_employee_type %></td>
    <td><%=h plan.special_district %></td>
    <td><%=h plan.plan_type1 %></td>
    <td><%=h plan.plan_type2 %></td>
    <td><%=h plan.plan_type3 %></td>
    <td><%=h plan.url %></td>
    <td><%=h plan.url_title %></td>
    <td><%=h plan.admin_url %></td>
    <td><%=h plan.admin_url_title %></td>
    <td><%=h plan.tpa_url %></td>
    <td><%=h plan.tpa_url_title %></td>
    <td><%=h plan.spd_url %></td>
    <td><%=h plan.spd_url_title %></td>
    <td><%= link_to 'Show', plan_path(@agency, plan) %></td>
    <td><%= link_to 'Edit', edit_plan_path(@agency, plan) %></td>
    <td><%= link_to 'Destroy', plan_path(@agency, plan), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New plan', new_plan_path %>

app/views/plans/new.html.erb
<div id="content-no-sidebar">
<h2>New plan</h2>

<%= error_messages_for :plan %>

<% form_for(:plan, :url => plans_path) do |f| %>
  <p>
    <b>Name</b><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <b>Name2</b><br />
    <%= f.text_field :name2 %>
  </p>

  <p>
    <b>Start date</b><br />
    <%= f.date_select :start_date %>
  </p>

  <p>
    <b>End date</b><br />
    <%= f.date_select :end_date %>
  </p>

  <p>
    <b>Covered employees</b><br />
    <%= f.text_area :covered_employees %>
  </p>

  <p>
    <b>Catchall employees</b><br />
    <%= f.text_area :catchall_employees %>
  </p>

  <p>
    <b>Description</b><br />
    <%= f.text_area :description %>
  </p>

  <p>
    <b>Service description</b><br />
    <%= f.text_area :service_description %>
  </p>

  <p>
    <b>Comments</b><br />
    <%= f.text_area :comments %>
  </p>

  <p>
    <b>Status</b><br />
    <%= f.text_field :status %>
  </p>

  <p>
    <b>Govt employee type</b><br />
    <%= f.text_field :govt_employee_type %>
  </p>

  <p>
    <b>Special district</b><br />
    <%= f.text_field :special_district %>
  </p>

  <p>
    <b>Plan type1</b><br />
    <%= f.text_field :plan_type1 %>
  </p>

  <p>
    <b>Plan type2</b><br />
    <%= f.text_field :plan_type2 %>
  </p>

  <p>
    <b>Plan type3</b><br />
    <%= f.text_field :plan_type3 %>
  </p>

  <p>
    <b>Url</b><br />
    <%= f.text_field :url %>
  </p>

  <p>
    <b>Url title</b><br />
    <%= f.text_field :url_title %>
  </p>

  <p>
    <b>Admin url</b><br />
    <%= f.text_field :admin_url %>
  </p>

  <p>
    <b>Admin url title</b><br />
    <%= f.text_field :admin_url_title %>
  </p>

  <p>
    <b>Tpa url</b><br />
    <%= f.text_field :tpa_url %>
  </p>

  <p>
    <b>Tpa url title</b><br />
    <%= f.text_field :tpa_url_title %>
  </p>

  <p>
    <b>Spd url</b><br />
    <%= f.text_field :spd_url %>
  </p>

  <p>
    <b>Spd url title</b><br />
    <%= f.text_field :spd_url_title %>
  </p>

  <p>
    <%= submit_tag "Create" %>
  </p>
<% end %>

<%= link_to 'Back', plans_path %>

</div>

app/views/plans/show.html.erb
<p>
  <b>Name:</b>
  <%=h @plan.name %>
</p>

<p>
  <b>Name2:</b>
  <%=h @plan.name2 %>
</p>

<p>
  <b>Start date:</b>
  <%=h @plan.start_date %>
</p>

<p>
  <b>End date:</b>
  <%=h @plan.end_date %>
</p>

<p>
  <b>Covered employees:</b>
  <%=h @plan.covered_employees %>
</p>

<p>
  <b>Catchall employees:</b>
  <%=h @plan.catchall_employees %>
</p>

<p>
  <b>Description:</b>
  <%=h @plan.description %>
</p>

<p>
  <b>Service description:</b>
  <%=h @plan.service_description %>
</p>

<p>
  <b>Comments:</b>
  <%=h @plan.comments %>
</p>

<p>
  <b>Status:</b>
  <%=h @plan.status %>
</p>

<p>
  <b>Govt employee type:</b>
  <%=h @plan.govt_employee_type %>
</p>

<p>
  <b>Special district:</b>
  <%=h @plan.special_district %>
</p>

<p>
  <b>Plan type1:</b>
  <%=h @plan.plan_type1 %>
</p>

<p>
  <b>Plan type2:</b>
  <%=h @plan.plan_type2 %>
</p>

<p>
  <b>Plan type3:</b>
  <%=h @plan.plan_type3 %>
</p>

<p>
  <b>Url:</b>
  <%=h @plan.url %>
</p>

<p>
  <b>Url title:</b>
  <%=h @plan.url_title %>
</p>

<p>
  <b>Admin url:</b>
  <%=h @plan.admin_url %>
</p>

<p>
  <b>Admin url title:</b>
  <%=h @plan.admin_url_title %>
</p>

<p>
  <b>Tpa url:</b>
  <%=h @plan.tpa_url %>
</p>

<p>
  <b>Tpa url title:</b>
  <%=h @plan.tpa_url_title %>
</p>

<p>
  <b>Spd url:</b>
  <%=h @plan.spd_url %>
</p>

<p>
  <b>Spd url title:</b>
  <%=h @plan.spd_url_title %>
</p>


<%= link_to 'Edit', edit_plan_path(@agency, @plan) %> |
<%= link_to 'Back', plans_path %>